api:
    entities:
        Oro\Bundle\IntegrationBundle\Entity\Channel:
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
            fields:
                mappingSettings:
                    exclude: true
                connectors:
                    exclude: true
                editMode:
                    exclude: true
                previouslyEnabled:
                    exclude: true
                synchronizationSettings:
                    exclude: true
                defaultBusinessUnitOwner:
                    exclude: true
                defaultUserOwner:
                    exclude: true
                organization:
                    exclude: true
