sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit -c . --testsuite="Project Unit Tests"
  - ./vendor/bin/phpcs ./src -p --encoding=utf-8 --extensions=php --standard=psr2
