sudo: required

language: php

php:
    - 5.5
    - 5.6
    - 7.0

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - phpenv config-add travis.php.ini
  - travis_retry travis_wait composer install --prefer-dist --optimize-autoloader --no-interaction  --no-suggest

script: 
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs ./src -p --encoding=utf-8 --extensions=php --standard=psr2
