styles:
    inputs:
        - 'bundles/bowerassets/font-awesome/css/font-awesome.css'
        - 'bundles/bowerassets/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css'
        - 'bundles/oroui/css/less/uniform.less'
        - 'bundles/oroui/css/less/font-awesome.less'
        - 'bundles/oroui/css/less/base.less'
        - 'bundles/oroui/css/less/desktop/form.less'
    filters: ['cssrewrite', 'cssmin']
    output: 'css/layout/base/styles.css'
