parameters:
    oro_form.validator.constraint_factory.class: Oro\Bundle\FormBundle\Validator\ConstraintFactory
    oro_form.provider.html_tag_provider.class:   Oro\Bundle\FormBundle\Provider\HtmlTagProvider
    oro_form.event.event_dispatcher.class:       Oro\Bundle\FormBundle\Event\EventDispatcher

services:
    oro_form.validator.constraint_factory:
        class: %oro_form.validator.constraint_factory.class%

    oro_form.twig.form_extension:
        class: Oro\Bundle\FormBundle\Twig\FormExtension
        public: false
        tags:
            - { name: twig.extension }

    oro_form.model.update_handler:
        class: 'Oro\Bundle\FormBundle\Model\UpdateHandler'
        arguments:
            - '@request_stack'
            - '@session'
            - '@oro_ui.router'
            - '@oro_entity.doctrine_helper'
            - '@oro_form.form.handler.default'
            - '@oro_form.registry.form_template_data_provider'

    oro_form.provider.html_tag_provider:
        class: %oro_form.provider.html_tag_provider.class%

    oro_form.count_query_optimization_listener:
        class: Oro\Bundle\FormBundle\EventListener\CountQueryOptimizationListener
        tags:
            - { name: kernel.event_listener, event: oro.entity.count_query.optimize, method: onOptimize }

    oro_form.event.event_dispatcher:
        class: %oro_form.event.event_dispatcher.class%
        arguments:
            - '@event_dispatcher'

    oro_form.doctrine.orm.validator_initializer:
        class: Oro\Bundle\FormBundle\Validator\DoctrineInitializer
        public: false
        decorates: doctrine.orm.validator_initializer
        arguments:
            - '@oro_form.doctrine.orm.validator_initializer.inner'

    oro_form.registry.form_template_data_provider:
        public: false
        class: 'Oro\Bundle\FormBundle\Model\FormTemplateDataProviderRegistry'
        arguments: ['@service_container']

    oro_form.registry.form_handler:
        public: false
        class: 'Oro\Bundle\FormBundle\Model\FormHandlerRegistry'

    oro_form.form.handler.default:
        public: false
        class: 'Oro\Bundle\FormBundle\Form\Handler\FormHandler'
        arguments:
            - '@oro_form.event.event_dispatcher'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_form.form.handler }
