config:
    shim:
        'jquery.validate':
            deps:
                - 'jquery'
    map:
        '*':
            'jquery.validate': 'oroform/js/extend/validate'
        'oroform/js/extend/validate':
            'jquery.validate': 'jquery.validate'
    paths:
        'jquery.validate': 'bundles/bowerassets/jquery-validate/jquery.validate.js'
        'oroform/js/app/views/form-validate-view': 'bundles/oroform/js/app/views/form-validate-view.js'
        'oro/select2-component': 'bundles/oroform/js/app/components/select2-component.js'
