services:
    oro_workflow.layout.block_type.workflow_transition_form:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            -
                - setOptionsConfig
                -
                    -
                        form: {required: true}
                        transition: {required: true}
            - [setName, ['workflow_transition_form']]
        tags:
            - { name: layout.block_type, alias: workflow_transition_form }

    oro_workflow.layout.block_type.workflow_transition_form_fields:
        parent: oro_workflow.layout.block_type.workflow_transition_form
        calls:
            -
                - setOptionsConfig
                -
                    -
                        form: {required: true}
            - [setName, ['workflow_transition_form_fields']]
        tags:
            - { name: layout.block_type, alias: workflow_transition_form_fields }

    oro_workflow.layout.block_type.workflow_transition_form_actions:
        parent: oro_workflow.layout.block_type.workflow_transition_form
        calls:
            -
                - setOptionsConfig
                -
                    -
                        form: {required: true}
                        formAction: {required: true}
            - [setName, ['workflow_transition_form_actions']]
        tags:
            - { name: layout.block_type, alias: workflow_transition_form_actions }
