services:
    oro_layout.block_type.abstract_attribute_type:
        abstract: true
        arguments:
            - '@oro_entity_extend.manager.attribute_manager'
        class: 'Oro\Bundle\EntityExtendBundle\Layout\Block\Type\AbstractAttributeType'

    oro_layout.block_type.attribute_text:
        parent: oro_layout.block_type.abstract_attribute_type
        class: 'Oro\Bundle\EntityExtendBundle\Layout\Block\Type\AttributeTextType'
        tags:
             - { name: layout.block_type, alias: attribute_text }

    oro_layout.block_type.attribute_percent:
        parent: oro_layout.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_percent']]
        tags:
             - { name: layout.block_type, alias: attribute_percent }

    oro_layout.block_type.attribute_money:
        parent: oro_layout.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_money']]
        tags:
             - { name: layout.block_type, alias: attribute_money }

    oro_layout.block_type.attribute_date:
        parent: oro_layout.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_date']]
        tags:
             - { name: layout.block_type, alias: attribute_date }

    oro_layout.block_type.attribute_datetime:
        parent: oro_layout.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_datetime']]
        tags:
             - { name: layout.block_type, alias: attribute_datetime }

    oro_layout.block_type.attribute_multiselect:
        parent: oro_layout.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_multiselect']]
        tags:
             - { name: layout.block_type, alias: attribute_multiselect }


