services:
    oro_entity_extend.block_type.abstract_attribute_type:
        abstract: true
        arguments:
            - '@oro_entity_extend.manager.attribute_manager'
        class: 'Oro\Bundle\EntityExtendBundle\Layout\Block\Type\AbstractAttributeType'

    oro_entity_extend.block_type.attribute_text:
        parent: oro_entity_extend.block_type.abstract_attribute_type
        class: 'Oro\Bundle\EntityExtendBundle\Layout\Block\Type\AttributeTextType'
        tags:
             - { name: layout.block_type, alias: attribute_text }

    oro_entity_extend.block_type.attribute_percent:
        parent: oro_entity_extend.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_percent']]
        tags:
             - { name: layout.block_type, alias: attribute_percent }

    oro_entity_extend.block_type.attribute_money:
        parent: oro_entity_extend.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_money']]
        tags:
             - { name: layout.block_type, alias: attribute_money }

    oro_entity_extend.block_type.attribute_date:
        parent: oro_entity_extend.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_date']]
        tags:
             - { name: layout.block_type, alias: attribute_date }

    oro_entity_extend.block_type.attribute_datetime:
        parent: oro_entity_extend.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_datetime']]
        tags:
             - { name: layout.block_type, alias: attribute_datetime }

    oro_entity_extend.block_type.attribute_multiselect:
        parent: oro_entity_extend.block_type.abstract_attribute_type
        calls:
            - [setName, ['attribute_multiselect']]
        tags:
             - { name: layout.block_type, alias: attribute_multiselect }

    oro_entity_extend.block_type.attribute_block_type_mapper:
        class: 'Oro\Bundle\EntityExtendBundle\Layout\Block\Type\AttributeBlockTypeMapper'
        calls:
            - [addBlockTypeByAttributeType, ['string', 'attribute_text']]
            - [addBlockTypeByAttributeType, ['text', 'attribute_text']]
            - [addBlockTypeByAttributeType, ['bigint', 'attribute_text']]
            - [addBlockTypeByAttributeType, ['integer', 'attribute_text']]
            - [addBlockTypeByAttributeType, ['float', 'attribute_text']]
            - [addBlockTypeByAttributeType, ['smallint', 'attribute_text']]
            - [addBlockTypeByAttributeType, ['decimal', 'attribute_text']]
            - [addBlockTypeByAttributeType, ['percent', 'attribute_percent']]
            - [addBlockTypeByAttributeType, ['currency', 'attribute_money']]
            - [addBlockTypeByAttributeType, ['date', 'attribute_date']]
            - [addBlockTypeByAttributeType, ['datetime', 'attribute_datetime']]
            - [addBlockTypeByAttributeType, ['multiEnum', 'attribute_multiselect']]
