services:
    oro_layout.block_type.abstract_attribute_type:
        abstract: true
        arguments:
            - '@oro_entity_extend.manager.attribute_manager'
        class: 'Oro\Bundle\EntityExtendBundle\Layout\Block\Type\AbstractAttributeType'

    oro_layout.block_type.attribute_text:
        parent: oro_layout.block_type.abstract_attribute_type
        class: 'Oro\Bundle\EntityExtendBundle\Layout\Block\Type\AttributeTextType'
        tags:
             - { name: layout.block_type, alias: attribute_text }
