Oro\Bundle\UIBundle\Model\TreeCollection:
    constraints:
        - Oro\Bundle\UIBundle\Validator\Constraints\MoveToChild: ~
    properties:
        source:
            - NotBlank: ~
        target:
            - NotBlank: ~
