assets:
    css:
      'orodatagrid':
          - 'bundles/bowerassets/backgrid/lib/backgrid.css'
          - 'bundles/bowerassets/backgrid-paginator/backgrid-paginator.css'
          - 'bundles/orodatagrid/css/scss/main.scss'
