Oro\Bundle\CalendarBundle\Entity\CalendarEvent:
    properties:
        title:
            - NotBlank:     ~
            - Length:
                max: 255
        start:
            - DateTime:     ~
            - NotBlank:     ~
            - Oro\Bundle\CalendarBundle\Validator\Constraints\DateEarlierThan: end
        end:
            - DateTime:     ~
            - NotBlank:     ~

Oro\Bundle\CalendarBundle\Entity\CalendarProperty:
    properties:
        targetCalendar:
            - NotBlank:     ~
        calendarAlias:
            - NotBlank:     ~
            - Length:
                max: 32
        calendar:
            - NotBlank:     ~
        backgroundColor:
            - Length:
                max: 7

Oro\Bundle\CalendarBundle\Entity\SystemCalendar:
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max: 255

Oro\Bundle\CalendarBundle\Entity\Recurrence:
    constraints:
        - Oro\Bundle\CalendarBundle\Validator\Constraints\Recurrence: ~
    properties:
        recurrenceType:
            - Choice: { callback: [Oro\Bundle\CalendarBundle\Model\Recurrence, getRecurrenceTypesValues] }
        interval:
            - Range:
                min: 1
                max: 999
        instance:
            - Range:
                min: 1
                max: 5
        dayOfWeek:
            - Choice:
                multiple: true
                callback: [Oro\Bundle\CalendarBundle\Model\Recurrence, getDaysOfWeekValues]
        dayOfMonth:
            - Range:
                min: 1
                max: 31
        monthOfYear:
            - Range:
                min: 1
                max: 12
        startTime:
            - DateTime: ~
            - NotBlank: ~
        endTime:
            - DateTime: ~
        occurrences:
            - Range:
                min: 1
                max: 999
