parameters:
    oro_translation.form.type.translatable_entity.class:     Oro\Bundle\TranslationBundle\Form\Type\TranslatableEntityType
    oro_translation.form.extension.translatable_choice.class: Oro\Bundle\TranslationBundle\Form\Extension\TranslatableChoiceTypeExtension

services:
    oro_translation.form.type.translatable_entity:
        class: '%oro_translation.form.type.translatable_entity.class%'
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: translatable_entity }

    oro_translation.form.type.select2_translatable_entity:
        class: Oro\Bundle\TranslationBundle\Form\Type\Select2TranslatableEntityType
        tags:
            - { name: form.type, alias: oro_select2_translatable_entity }

    oro_translation.form.extension.translatable_choice:
        class: '%oro_translation.form.extension.translatable_choice.class%'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType, alias: choice }

    oro_translation.form.type.add_language:
        class: 'Oro\Bundle\TranslationBundle\Form\Type\AddLanguageType'
        arguments:
            - '@oro_translation.repository.language'
            - '@oro_locale.settings'
            - '@oro_translation.statistic_provider'
            - '@translator'
        tags:
            - { name: form.type, alias: oro_translation_add_language }

    oro_translationr.form.type.filter.language:
        class: 'Oro\Bundle\TranslationBundle\Form\Type\Filter\LanguageFilterType'
        arguments: 
            - '@oro_locale.formatter.language_code'
        tags:
            - { name: form.type, alias: oro_translation_filter_language }
