services:
    oro_security_test.faker_generator:
        class: Faker\Generator

    oro_security_test.provider.xss_payload_provider:
        class: Oro\Bundle\TestFrameworkBundle\Provider\XssPayloadProvider

    oro_security_test.faker.provider.xss:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Faker\Provider\XssProvider
        arguments:
            - '@oro_security_test.faker_generator'
            - '@oro_security_test.provider.xss_payload_provider'
