services:
    oro_importexport.async.pre_export:
        class: 'Oro\Bundle\ImportExportBundle\Async\Export\PreExportMessageProcessor'
        arguments:
            - '@oro_importexport.handler.export'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@oro_entity.doctrine_helper'
            - '@security.token_storage'
            - '@logger'
            - '@oro_message_queue.job.dependent_job_service'
            - '%oro_importexport.export.size_of_batch%'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
        calls:
            - [setTokenSerializer, ['@oro_security.token_serializer']]

    oro_importexport.async.export:
        class: 'Oro\Bundle\ImportExportBundle\Async\Export\ExportMessageProcessor'
        arguments:
            - '@oro_importexport.handler.export'
            - '@oro_message_queue.job.runner'
            - '@oro_entity.doctrine_helper'
            - '@security.token_storage'
            - '@logger'
            - '@oro_message_queue.job.storage'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
        calls:
            - [setTokenSerializer, ['@oro_security.token_serializer']]

    oro_importexport.async.post_export:
        class: 'Oro\Bundle\ImportExportBundle\Async\Export\PostExportMessageProcessor'
        arguments:
            - '@oro_importexport.handler.export'
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_message_queue.job.storage'
            - '@oro_importexport.async.import_export_result_summarizer'
            - '@oro_config.user'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.pre_cli_import:
        class: 'Oro\Bundle\ImportExportBundle\Async\Import\PreCliImportMessageProcessor'
        arguments:
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_message_queue.job.dependent_job_service'
            - '@oro_importexport.file.file_manager'
            - '@oro_importexport.handler.import.cli'
            - '@oro_importexport.writer.writer_chain'
            - '%oro_importexport.export.size_of_batch%'
        calls:
            - [setConfigManager, ['@oro_config.user']]
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.cli_import:
        class: 'Oro\Bundle\ImportExportBundle\Async\Import\CliImportMessageProcessor'
        arguments:
            - '@oro_importexport.handler.import.cli'
            - '@oro_message_queue.job.runner'
            - '@oro_importexport.async.import_export_result_summarizer'
            - '@oro_message_queue.job.storage'
            - '@logger'
            - '@oro_importexport.file.file_manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.pre_http_import:
        class: 'Oro\Bundle\ImportExportBundle\Async\Import\PreHttpImportMessageProcessor'
        arguments:
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_message_queue.job.dependent_job_service'
            - '@oro_importexport.file.file_manager'
            - '@oro_importexport.handler.import.http'
            - '@oro_importexport.writer.writer_chain'
            - '%oro_importexport.export.size_of_batch%'
        calls:
            - [setConfigManager, ['@oro_config.user']]
            - [setManagerRegistry, ['@doctrine']]
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.http_import:
        class: 'Oro\Bundle\ImportExportBundle\Async\Import\HttpImportMessageProcessor'
        arguments:
            - '@oro_importexport.handler.import.http'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@security.token_storage'
            - '@oro_importexport.async.import_export_result_summarizer'
            - '@oro_message_queue.job.storage'
            - '@logger'
            - '@oro_importexport.file.file_manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
        calls:
            - [setTokenSerializer, ['@oro_security.token_serializer']]

    oro_importexport.async.send_import_notification:
        class: 'Oro\Bundle\ImportExportBundle\Async\SendImportNotificationMessageProcessor'
        arguments:
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_message_queue.job.storage'
            - '@oro_importexport.async.import_export_result_summarizer'
            - '@oro_config.user'
            - '@doctrine'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    #  since 2.1, will be removed in 2.3
    oro_importexport.async.send_import_error_notification:
        class: 'Oro\Bundle\ImportExportBundle\Async\SendImportErrorNotificationMessageProcessor'
        arguments:
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_config.user'
            - '@doctrine'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
