services:
    oro_importexport.async.export:
        class: Oro\Bundle\ImportExportBundle\Async\ExportMessageProcessor
        arguments:
            - '@oro_importexport.handler.export'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@oro_config.user'
            - '@oro_entity.doctrine_helper'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.cli_import:
        class: Oro\Bundle\ImportExportBundle\Async\Import\CliImportMessageProcessor
        arguments:
            - '@oro_importexport.handler.import.cli'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@oro_config.user'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.cli_import_validation:
        class: Oro\Bundle\ImportExportBundle\Async\Import\CliImportValidationMessageProcessor
        arguments:
            - '@oro_importexport.handler.import.cli'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@oro_config.user'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.abstract_http_import:
        class: Oro\Bundle\ImportExportBundle\Async\Import\AbstractChunkImportMessageProcessor
        abstract:  true
        arguments:
            - '@oro_importexport.handler.import.http'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@doctrine'
            - '@oro_config.user'
            - "@security.token_storage"
            - '@logger'

    oro_importexport.async.http_import:
        class: Oro\Bundle\ImportExportBundle\Async\Import\ChunkHttpImportMessageProcessor
        parent: oro_importexport.async.abstract_http_import
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.http_import_validation:
        class: Oro\Bundle\ImportExportBundle\Async\Import\ChunkHttpImportValidationMessageProcessor
        parent: oro_importexport.async.abstract_http_import
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.abstract_http_import_preparing:
        class: Oro\Bundle\ImportExportBundle\Async\Import\AbstractPreparingHttpImportMessageProcessor
        abstract:  true
        arguments:
            - '@oro_importexport.handler.import.http'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_importexport.file.split_csv_file'
            - '@doctrine'

    oro_importexport.async.http_import_validation_preparing:
        class: Oro\Bundle\ImportExportBundle\Async\Import\PreparingHttpImportValidationMessageProcessor
        parent: oro_importexport.async.abstract_http_import_preparing
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.http_import_preparing:
        class: Oro\Bundle\ImportExportBundle\Async\Import\PreparingHttpImportMessageProcessor
        parent: oro_importexport.async.abstract_http_import_preparing
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
