config:
    paths:
        'oroimportexport/js/importexport-manager': 'bundles/oroimportexport/js/importexport-manager.js'
        'oroimportexport/js/export-handler': 'bundles/oroimportexport/js/export-handler.js'
        'oroimportexport/js/app/views/import-export-buttons-view': 'bundles/oroimportexport/js/app/views/import-export-buttons-view.js'
        'oroimportexport/js/app/views/export-configurable-widget-view': 'bundles/oroimportexport/js/app/views/export-configurable-widget-view.js'
        'oroimportexport/js/app/views/export-configurable-template-widget-view': 'bundles/oroimportexport/js/app/views/export-configurable-template-widget-view.js'
        'oroimportexport/js/widget/import-dialog-widget': 'bundles/oroimportexport/js/widget/import-dialog-widget.js'
