datagrids:
    # Entity config entities grid
    entityconfig-grid:
        options:
            entityHint: entity
            toolbarOptions:
                pageSize:
                    default_per_page: 100
        acl_resource: oro_entityconfig_manage
        source:
            type: orm
            query:
                select:
                    - ce.id
                    - ce.updated
                    - ce.mode
                    - ce.data
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }
                where:
                    and:
                        - ce.mode <> 'Oro\Bundle\EntityConfigBundle\Entity\ConfigModel::MODE_HIDDEN'
        columns:
            updated:
                label: oro.ui.updated_at
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: oro_entityconfig_update
                params:
                    - id
            view_link:
                type: url
                route: oro_entityconfig_view
                params:
                    - id
        actions:
            # @TODO check why those actions dont have ACL
            view:
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                type: navigate
                label: oro.grid.action.update
                icon: pencil-square-o
                link: update_link
        sorters:
            columns:
                updated:
                    data_name: ce.updated
            disable_default_sorting: true
        filters:
            columns:
                updated:
                    type: datetime
                    data_name: ce.updated

    base-entityfields-grid:
        options:
            mode: client
            entityHint: fields
            toolbarOptions:
                pageSize:
                    default_per_page: 50
        source:
            type: orm
            query:
                select:
                    - cf.id
                    - ce.className
                    - cf.fieldName
                    - cf.type
                    - cf.mode
                    - ce.id as entity_id
                    - cf.data
                from:
                    - { table: OroEntityConfigBundle:FieldConfigModel, alias: cf }
                join:
                    inner:
                        - { join: cf.entity, alias: ce }
                where:
                    and:
                        - ce.id = :entity_id
                        - cf.mode <> 'Oro\Bundle\EntityConfigBundle\Entity\ConfigModel::MODE_HIDDEN'
        columns:
            fieldName:
                label: oro.entity_config.field_config.field_name.label
                frontend_type: string
            type:
                label: oro.entity_config.field_config.type.label
                frontend_type: html
                type: twig
                template: OroEntityConfigBundle:Config:fieldType.html.twig

        actions:
            # @TODO check why those actions dont have ACL
            update:
                type: navigate
                label: oro.grid.action.update
                icon: pencil-square-o
                link: update_link
                rowAction: true
        sorters:
            columns:
                fieldName:
                    data_name: cf.fieldName
                type:
                    data_name: cf.type
            default:
                fieldName: ASC
        filters: ~

    # Entity field datagrid
    entityfields-grid:
        extends: base-entityfields-grid
        # TODO: check oro_entityconfig_view acl (403) right now
        acl_resource: oro_entityconfig_manage
        properties:
            update_link:
                type: url
                route: oro_entityconfig_field_update
                params:
                    - id

    # Attribute fields datagrid
    attributes-grid:
        extends: base-entityfields-grid
        acl_resource: oro_attributes_manage
        source:
            type: orm
            query:
                where:
                    and:
                        - cfv_attribute_is_attribute.value = '1'
        properties:
            update_link:
                type: url
                route: oro_attribute_update
                params:
                    - id
        filters:
            columns:
                type:
                    type:      choice
                    data_name: cf.type
                    options:
                        field_options:
                            choices: "@oro_entity_extend.type.field->getTranslatedTypeChoices"
                            multiple: true

    # Audit entity log grid
    entity-audit-grid:
        options:
            entityHint: history
        acl_resource: oro_entityconfig_manage
        source:
            type: orm
            query:
                select:
                    - log
                    - >
                      CONCAT(
                        CONCAT(
                            CONCAT(u.firstName, ' '),
                            CONCAT(u.lastName, ' ')
                        ),
                        CONCAT(' - ', u.email)
                      ) as author
                from:
                    - { table: Oro\Bundle\EntityConfigBundle\Audit\Entity\ConfigLog, alias: log }
                join:
                    left:
                        user:
                            join: log.user
                            alias: u
                    inner:
                        diffs:
                            join: log.diffs
                            alias: diff
                            conditionType: WITH

        columns:
            author:
                label: oro.entity_config.config_log.user.label
                type: field
                frontend_type: string
            diffs:
                label: oro.entity_config.config_log.diffs.label
                type: twig
                template: OroEntityConfigBundle:Audit:data.html.twig
                frontend_type: html
                context:
                    config_manager: '@oro_entity_config.config_manager'
            loggedAt:
                label: oro.entity_config.config_log.logged_at.label
                type: field
                frontend_type: datetime

        sorters:
            columns:
                author:
                    data_name: author
                loggedAt:
                    data_name: log.loggedAt
            default:
                loggedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    audit-log-grid:
        extends: entity-audit-grid
        source:
            query:
                join:
                    inner:
                        diffs:
                            condition: diff.className = :objectClass AND diff.fieldName IS NULL
        columns:
            diffs:
                context:
                    is_entity: true

    auditfield-log-grid:
        extends: entity-audit-grid
        source:
            query:
                join:
                    inner:
                        diffs:
                            condition: diff.className = :objectClass AND diff.fieldName = :fieldName
        columns:
            diffs:
                context:
                    is_entity: false
                    field_name: ~ # set from buildBefore in event listener
