placeholders:
    placeholders:
        view_entity_sync_content_tags:
              items:
                  oro_entity_config_attributes_import_view: ~

        attributes_content_after:
              items:
                  oro_entity_config_attributes_import_index: ~

    items:
        oro_entity_config_attributes_import_view:
            applicable: "@oro_entity_config.placeholder.attributes_import_filter->isApplicableEntity($entity$)"
            template: OroEntityConfigBundle:Attribute:attributes_import_content_tag.html.twig
            data: "@oro_entity_config.placeholder.attributes_import_filter->getTagByEntity($entity$)"

        oro_entity_config_attributes_import_index:
            applicable: "@oro_entity_config.placeholder.attributes_import_filter->isApplicableAlias($entityAlias$)"
            template: OroEntityConfigBundle:Attribute:attributes_import_content_tag.html.twig
            data: "@oro_entity_config.placeholder.attributes_import_filter->getTagByAlias($entityAlias$)"
