urls:
    # Master Catalog
    - { route: 'oro_catalog_category_index' }
    - { route: 'oro_catalog_category_create', parameters: { id: '@category1.id' } }
    - { route: 'oro_catalog_category_update', parameters: { id: '@category1.id' } }

    # Products
    - { route: 'oro_product_index' }
    - { route: 'oro_product_create' }
    - { route: 'oro_product_update', parameters: { id: '@simple_product.id' } }
    - { route: 'oro_product_update', parameters: { id: '@configurable_product_variant_1.id' } }
    - { route: 'oro_product_update', parameters: { id: '@configurable_product.id' } }
    - { route: 'oro_product_view', parameters: { id: '@simple_product.id' } }
    - { route: 'oro_product_view', parameters: { id: '@configurable_product_variant_1.id' } }
    - { route: 'oro_product_view', parameters: { id: '@configurable_product.id' } }

    # Product Families
    - { route: 'oro_attribute_family_index', parameters: { alias: 'product' } }
    - { route: 'oro_attribute_family_create', parameters: { alias: 'product' }  }
    - { route: 'oro_attribute_family_view', parameters: { id: '@tshirt_family.id' } }
    - { route: 'oro_attribute_family_update', parameters: { id: '@tshirt_family.id' } }
#
#    # Product Attributes
#    - { route: 'oro_order_index' }
#    - { route: 'oro_order_create' }
#    - { route: 'oro_order_view', parameters: { id: '@order1.id' } }
#    - { route: 'oro_order_update', parameters: { id: '@order1.id' } }
#
    # Product Brands
    - { route: 'oro_product_brand_index' }
    - { route: 'oro_product_brand_create' }
    - { route: 'oro_product_brand_update', parameters: { id: '@brand.id' }, options: { disable_select2_checks: true } }

    # Price Attributes
    - { route: 'oro_pricing_price_attribute_price_list_index' }
    - { route: 'oro_pricing_price_attribute_price_list_create' }
    - { route: 'oro_pricing_price_attribute_price_list_view', parameters: { id: '@price_attribute.id' } }
    - { route: 'oro_pricing_price_attribute_price_list_update', parameters: { id: '@price_attribute.id' }, options: { disable_select2_checks: true } }
