urls:
    # Promotions
    - { route: 'oro_promotion_index' }
    - { route: 'oro_promotion_create' }
    - { route: 'oro_promotion_update', parameters: { id: '@order_promotion.id' }, options: { disable_select2_checks: true } }
    - { route: 'oro_promotion_update', parameters: { id: '@line_item_promotion.id' }, options: { disable_select2_checks: true } }
    - { route: 'oro_promotion_update', parameters: { id: '@bogo_promotion.id' }, options: { disable_select2_checks: true } }
    - { route: 'oro_promotion_update', parameters: { id: '@shipping_promotion.id' }, options: { disable_select2_checks: true } }
    - { route: 'oro_promotion_view', parameters: { id: '@order_promotion.id' } }
    - { route: 'oro_promotion_view', parameters: { id: '@line_item_promotion.id' } }
    - { route: 'oro_promotion_view', parameters: { id: '@bogo_promotion.id' } }
    - { route: 'oro_promotion_view', parameters: { id: '@shipping_promotion.id' } }

    # Coupons
    - { route: 'oro_promotion_coupon_index' }
    - { route: 'oro_promotion_coupon_create' }
    - { route: 'oro_promotion_coupon_view', parameters: { id: '@coupon_1.id' } }
    - { route: 'oro_promotion_coupon_update', parameters: { id: '@coupon_1.id' }, options: { disable_select2_checks: true } }

     # Web Catalogs
    - { route: 'oro_web_catalog_index' }
    - { route: 'oro_web_catalog_create' }
    - { route: 'oro_web_catalog_view', parameters: { id: '@xss_web_catalog.id' } }
    - { route: 'oro_web_catalog_update', parameters: { id: '@xss_web_catalog.id' } }

    # Web Catalogs/Content Nodes
    - { route: 'oro_content_node_update_root', parameters: { id: '@xss_web_catalog.id' } }
    - { route: 'oro_content_node_create', parameters: { id: '@content_node_1.id' } }
    - { route: 'oro_content_node_update', parameters: { id: '@content_node_1.id' } }
    - { route: 'oro_content_node_update', parameters: { id: '@content_node_2.id' } }
    - { route: 'oro_content_node_update', parameters: { id: '@content_node_3.id' } }
    - { route: 'oro_content_node_update', parameters: { id: '@content_node_4.id' } }

    # Landing Pages
    - { route: 'oro_cms_page_index' }
    - { route: 'oro_cms_page_create' }
    - { route: 'oro_cms_page_view', parameters: { id: '@landing_page.id' } }
    - { route: 'oro_cms_page_update', parameters: { id: '@landing_page.id' }, options: { disable_select2_checks: true } }

    # Content Blocks
    - { route: 'oro_cms_content_block_index' }
    - { route: 'oro_cms_content_block_create' }
    - { route: 'oro_cms_content_block_view', parameters: { id: '@content_block.id' } }
    - { route: 'oro_cms_content_block_update', parameters: { id: '@content_block.id' }, options: { disable_select2_checks: true } }

    #Customer Login Pages
    - { route: 'oro_cms_loginpage_index' }
    - { route: 'oro_cms_loginpage_create' }
    - { route: 'oro_cms_loginpage_view', parameters: { id: '@login_page.id' } }
    - { route: 'oro_cms_loginpage_update', parameters: { id: '@login_page.id' }, options: { disable_select2_checks: true } }
