urls:
    # Product Tax Codes
    - { route: 'oro_tax_product_tax_code_index' }
    - { route: 'oro_tax_product_tax_code_create' }
    - { route: 'oro_tax_product_tax_code_view', parameters: { id: '@product_tax_code.id' } }
    - { route: 'oro_tax_product_tax_code_update', parameters: { id: '@product_tax_code.id' }, options: { disable_select2_checks: true } }

    # Customer Tax Codes
    - { route: 'oro_tax_customer_tax_code_index' }
    - { route: 'oro_tax_customer_tax_code_create' }
    - { route: 'oro_tax_customer_tax_code_view', parameters: { id: '@customer_tax_code.id' } }
    - { route: 'oro_tax_customer_tax_code_update', parameters: { id: '@customer_tax_code.id' }, options: { disable_select2_checks: true } }

    # Taxes
    - { route: 'oro_tax_index' }
    - { route: 'oro_tax_create' }
    - { route: 'oro_tax_view', parameters: { id: '@tax.id' } }
    - { route: 'oro_tax_update', parameters: { id: '@tax.id' }, options: { disable_select2_checks: true } }

    # Tax Rules
    - { route: 'oro_tax_rule_index' }
    - { route: 'oro_tax_rule_create' }
    - { route: 'oro_tax_rule_view', parameters: { id: '@tax_rule.id' } }
    - { route: 'oro_tax_rule_update', parameters: { id: '@tax_rule.id' }, options: { disable_select2_checks: true } }

    # Tax Jurisdictions
    - { route: 'oro_tax_jurisdiction_index' }
    - { route: 'oro_tax_jurisdiction_create' }
    - { route: 'oro_tax_jurisdiction_view', parameters: { id: '@tax_jurisdiction.id' } }
    - { route: 'oro_tax_jurisdiction_update', parameters: { id: '@tax_jurisdiction.id' }, options: { disable_select2_checks: true } }
