urls:
    # Shopping List
    - { route: 'oro_shopping_list_index' }
    - { route: 'oro_shopping_list_view', parameters: { id: '@shoppinglist1.id' } }

    # Quote
    - { route: 'oro_sale_quote_index' }
    - { route: 'oro_sale_quote_create' }
    - { route: 'oro_sale_quote_view', parameters: { id: '@quote.id' } }
    - { route: 'oro_sale_quote_update', parameters: { id: '@quote.id' } }

    # RFP Request
    - { route: 'oro_rfp_request_index' }
    - { route: 'oro_rfp_request_view', parameters: { id: '@rfp_request.id' } }
    - { route: 'oro_rfp_request_update', parameters: { id: '@rfp_request.id' } }
    - { route: 'oro_rfp_request_create_order', parameters: { id: '@rfp_request.id' } }

    # Order
    - { route: 'oro_order_index' }
    - { route: 'oro_order_create' }
    - { route: 'oro_order_view', parameters: { id: '@order1.id' } }
    - { route: 'oro_order_update', parameters: { id: '@order1.id' } }

    # Price List
    - { route: 'oro_pricing_price_list_index' }
    - { route: 'oro_pricing_price_list_create' }
    - { route: 'oro_pricing_price_list_view', parameters: { id: '@pricelist.id' } }
    - { route: 'oro_pricing_price_list_update', parameters: { id: '@pricelist.id' } }

    # Payment Terms
    - { route: 'oro_payment_term_index' }
    - { route: 'oro_payment_term_create' }
    - { route: 'oro_payment_term_view', parameters: { id: '@paymentTerm.id' } }
    - { route: 'oro_payment_term_update', parameters: { id: '@paymentTerm.id' } }
