urls:
    - { route: 'oro_product_frontend_product_view', parameters: { id: '@simple_product.id' } }
    - { route: 'oro_product_frontend_product_view', parameters: { id: '@configurable_product.id' } }
