urls:
    - { route: 'oro_catalog_frontend_product_allproducts' }
    - { route: 'oro_frontend_root' }
    - { route: 'oro_product_frontend_product_index' }
    - { route: 'oro_product_frontend_product_index', parameters: { categoryId: '@category1.id', includeSubcategories: true } }
    - { route: 'oro_website_search_results' }
    - { route: 'oro_website_search_results', parameters: { search: '<script>(window.xss=window.xss||[]).push("website_search")</script>' } }
