urls:
    # RFP Request
    - { route: 'oro_rfp_frontend_request_index' }
    - { route: 'oro_rfp_frontend_request_create' }
    - { route: 'oro_rfp_frontend_request_view', parameters: { id: '@rfp_request.id' } }
    - { route: 'oro_rfp_frontend_request_update', parameters: { id: '@rfp_request.id' } }

    # Quote
    - { route: 'oro_sale_quote_frontend_index' }
    - { route: 'oro_sale_quote_frontend_view', parameters: { id: '@quote.id' } }
    - { route: 'oro_sale_quote_frontend_choice', parameters: { id: '@quote_demand.id' } }

    # Order
    - { route: 'oro_order_frontend_index' }
    - { route: 'oro_checkout_frontend_open_orders' }
    - { route: 'oro_order_frontend_view', parameters: { id: '@order1.id' } }
