styles:
    inputs:
        - 'bundles/orodatagrid/blank/scss/variables/launcher-item-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/more-bar-holder-config.scss'
        - 'bundles/orodatagrid/blank/scss/styles.scss'
