services:
    oro_entity.validator.entity_field_fallback_value:
        class: 'Oro\Bundle\EntityBundle\Validator\Constraints\EntityFieldFallbackValueValidator'
        arguments: [ '@oro_entity.fallback.resolver.entity_fallback_resolver' ]
        tags:
            - { name: validator.constraint_validator, alias: oro_entity_entity_field_fallback_value_validator }
