doctrine:
    orm:
        entity_managers:
            message_queue_job:
                connection: default
                mappings:
                    OroMessageQueueBundle: ~

oro_message_queue:
    persistent_services:
        - 'kernel'
        - 'oro_message_queue.client.message_processor_registry'
        - 'oro_message_queue.client.delegate_message_processor'
        - 'oro_message_queue.client.route_message_processor'
        - 'oro_message_queue.client.config'
        - 'oro_message_queue.client.created_queues'
        - 'oro_message_queue.log.consumer_state'
        - 'oro_message_queue.log.message_to_array_converter'
        - 'oro_message_queue.log.message_processor_class_provider'
    persistent_processors:
        - 'oro_message_queue.client.route_message_processor'
        - 'oro_message_queue.job.calculate_root_job_status_processor'
        - 'oro_message_queue.job.calculate_root_job_progress_processor'
        - 'oro_message_queue.job.dependent_job_processor'
    time_before_stale:
        default: 1800
        jobs: ~

monolog:
    handlers:
        # write all log records to the consume CLI command console output
        message_queue.consumer.console:
            type: service
            id: oro_message_queue.log.handler.console
            # should be one of the first handlers to avoid cancelling of this handler
            # by another not bubbled handler with higher priority
            priority: 256
