services:
    oro_entity_config.block_type.attribute_text:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_text']]
            -
                - setOptionsConfig
                -
                    -
                        entity: {required: true}
                        property_path: {required: true}
                        value: {default: '=data["property_accessor"].getValue(entity, property_path)'}
        tags:
             - { name: layout.block_type, alias: attribute_text }

    oro_entity_config.block_type.attribute_percent:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_percent']]
            - [setParent, ['attribute_text']]
        tags:
             - { name: layout.block_type, alias: attribute_percent }

    oro_entity_config.block_type.attribute_currency:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_currency']]
            - [setParent, ['attribute_text']]
        tags:
             - { name: layout.block_type, alias: attribute_currency }

    oro_entity_config.block_type.attribute_date:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_date']]
            - [setParent, ['attribute_text']]
        tags:
             - { name: layout.block_type, alias: attribute_date }

    oro_entity_config.block_type.attribute_datetime:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_datetime']]
            - [setParent, ['attribute_text']]
        tags:
             - { name: layout.block_type, alias: attribute_datetime }

    oro_entity_config.block_type.attribute_multiselect:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_multiselect']]
            - [setParent, ['attribute_text']]
        tags:
             - { name: layout.block_type, alias: attribute_multiselect }

    oro_entity_config.block_type.attribute_localize_fallback:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_localized_fallback']]
            - [setParent, ['attribute_text']]
            - [setOptionsConfig, [{translated_value: {default: '=data["locale"].getLocalizedValue(value)'}}]]
        tags:
             - { name: layout.block_type, alias: attribute_localize_fallback }
