services:
    oro_entity_config.block_type.attribute:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute']]
        tags:
             - { name: layout.block_type, alias: attribute }

    oro_entity_config.block_type.attribute_text:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_text']]
            - [setParent, ['attribute']]
        tags:
             - { name: layout.block_type, alias: attribute_text }

    oro_entity_config.block_type.attribute_percent:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_percent']]
            - [setParent, ['attribute']]
        tags:
             - { name: layout.block_type, alias: attribute_percent }

    oro_entity_config.block_type.attribute_currency:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_currency']]
            - [setParent, ['attribute']]
        tags:
             - { name: layout.block_type, alias: attribute_currency }

    oro_entity_config.block_type.attribute_date:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_date']]
            - [setParent, ['attribute']]
        tags:
             - { name: layout.block_type, alias: attribute_date }

    oro_entity_config.block_type.attribute_datetime:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_datetime']]
            - [setParent, ['attribute']]
        tags:
             - { name: layout.block_type, alias: attribute_datetime }

    oro_entity_config.block_type.attribute_multiselect:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['attribute_multiselect']]
            - [setParent, ['attribute']]
        tags:
             - { name: layout.block_type, alias: attribute_multiselect }
