placeholders:
    placeholders: ~

    items:
        oro_add_note_button:
            template: OroNoteBundle:Note:addButton.html.twig
            acl: [oro_note_create, oro_note_view]

        oro_add_note_link:
            template: OroNoteBundle:Note:addLink.html.twig
            acl: [oro_note_create, oro_note_view]
#@todo: check if this placeholder is needed
        oro_notes:
            template: OroNoteBundle:Note:notes.html.twig
            acl: oro_note_view
