parameters:
    oro_note.entity.class:                              Oro\Bundle\NoteBundle\Entity\Note
    oro_note.manager.class:                             Oro\Bundle\NoteBundle\Entity\Manager\NoteManager
    oro_note.manager.api.class:                         Oro\Bundle\NoteBundle\Entity\Manager\ApiEntityManager
    oro_note.activity_list.provider.class:              Oro\Bundle\NoteBundle\Provider\NoteActivityListProvider

services:
    oro_note.manager:
        class: %oro_note.manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_security.security_facade'
            - '@oro_security.acl_helper'
            - '@oro_entity.entity_name_resolver'
            - '@oro_attachment.provider.attachment'
            - '@oro_attachment.manager'

    oro_note.manager.api:
        class: %oro_note.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_note.entity.class%
            - '@doctrine.orm.entity_manager'

    oro_note.activity_list.provider:
        class: %oro_note.activity_list.provider.class%
        arguments:
           - '@oro_entity.doctrine_helper'
           - '@oro_security.owner.entity_owner_accessor.link'
           - '@oro_activity.association_helper'
           - '@oro_comment.association_helper'
        tags:
           - {name: oro_activity_list.provider, priority: 40}
