Oro\Bundle\NoteBundle\Entity\Note:
    constraints:
        - Oro\Bundle\NoteBundle\Validator\Constraints\ContextNotEmpty: ~
    properties:
        message:
            - NotBlank:     ~
        organization:
            - NotBlank: ~
