parameters:
    oro_message_queue.consumption.interrupt_filepath: '%kernel.cache_dir%/mq/interrupt_consumption.meta'

services:
    oro_message_queue.consumption.extensions:
        class: 'Oro\Bundle\MessageQueueBundle\Consumption\Extension\ChainExtension'
        public: false
        arguments:
            - []
        calls:
            - ['setConsumerState', ['@oro_message_queue.log.consumer_state']]

    oro_message_queue.consumption.container_reset_extension:
        class: 'Oro\Bundle\MessageQueueBundle\Consumption\Extension\ContainerResetExtension'
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: 'oro_message_queue.consumption.extension', priority: -250, persistent: true }

    oro_message_queue.consumption.docrine_ping_connection_extension:
        class: 'Oro\Bundle\MessageQueueBundle\Consumption\Extension\DoctrinePingConnectionExtension'
        public: false
        arguments:
            - '@doctrine'
        tags:
            - { name: 'oro_message_queue.consumption.extension', priority: -210}

    oro_message_queue.consumption.docrine_clear_identity_map_extension:
        class: 'Oro\Bundle\MessageQueueBundle\Consumption\Extension\DoctrineClearIdentityMapExtension'
        public: false
        arguments:
            - '@doctrine'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: 'oro_message_queue.consumption.extension', priority: -200 }

    oro_message_queue.consumption.interrupt_consumption_extension:
        class: 'Oro\Bundle\MessageQueueBundle\Consumption\Extension\InterruptConsumptionExtension'
        public: false
        arguments:
            - '%oro_message_queue.consumption.interrupt_filepath%'
        calls:
            - ['setCacheState', ['@oro_message_queue.consumption.cache_state']]
        tags:
            - { name: 'oro_message_queue.consumption.extension' }

    oro_message_queue.consumption.token_storage_clearer_extension:
        class: 'Oro\Bundle\MessageQueueBundle\Consumption\Extension\TokenStorageClearerExtension'
        public: false
        arguments:
            - '@security.token_storage'
        tags:
            - { name: 'oro_message_queue.consumption.extension' }

    oro_message_queue.consumption.database_connections_clearer:
        class: Oro\Bundle\MessageQueueBundle\Consumption\Extension\DatabaseConnectionsClearer
        public: false
        arguments:
            - '@service_container'
            - '%doctrine.connections%'
        tags:
            - { name: oro_message_queue.consumption.clearer, priority: 10 }

    oro_message_queue.consumption.container_clearer:
        class: Oro\Bundle\MessageQueueBundle\Consumption\Extension\ContainerClearer
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: oro_message_queue.consumption.clearer }

    oro_message_queue.consumption.queue_consumer:
        class: 'Oro\Component\MessageQueue\Consumption\QueueConsumer'
        arguments:
            - '@oro_message_queue.transport.connection'
            - '@oro_message_queue.consumption.extensions'

    # needs to be register via DI due to BC
    oro_message_queue.command.consume_messages:
        class: 'Oro\Component\MessageQueue\Consumption\ConsumeMessagesCommand'
        arguments:
            - '@oro_message_queue.consumption.queue_consumer'
        tags:
            - { name: 'console.command' }

    oro_message_queue.listener.update_schema:
        class: 'Oro\Bundle\MessageQueueBundle\EventListener\UpdateSchemaListener'
        arguments:
            - '%oro_message_queue.consumption.interrupt_filepath%'
        tags:
            - { name: 'kernel.event_listener', event: 'oro.entity_extend.entity.schema.update', priority: -250, method: 'interruptConsumption' }

    oro_message_queue.consumption.cache_state:
        class: Oro\Bundle\MessageQueueBundle\Consumption\CacheState
        arguments:
            - '@oro_message_queue.consumption.cache_state_driver.dbal'

    oro_message_queue.consumption.cache_state_driver.dbal:
        class: Oro\Bundle\MessageQueueBundle\Consumption\StateDriver\DbalStateDriver
        public: false
        arguments:
            - 'cache'
            - '@doctrine'
            - '@logger'
